### ISSUE TITLE
Overriding Global Variables

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#30]
* Do not override global variables
	* archive.php line 19, I do not see any reason why this global variable is being used here
	* inc/extras.php line 105
	* inc/template-tags.php line 213, 221, 230, 231, 290, 298, 307, 308
	* index.php line 15

**Comment by justintadlock** [comment]
I assume in `archive.php` and `index.php` that they are intentionally not enforcing the `<!--more-->` tag by setting `$more = 1`.  I believe that's the only way to overwrite it.

For the `$authordata` global in `inc/extras.php`, that should be removed since it's a back-compat fix for earlier than WP 3.7.  The .ORG directory only allows for up to 3 versions of back-compat.

The other stuff in `inc/template-tags.php` looks all right since it's a custom comment walker.

**Comment by ideadude** [comment]
Removed the old back compat code from inc/extras.php https://github.com/strangerstudios/memberlite/commit/1c8a32d73f6332b367ccbdd3979c980ad9da569e

Left the other uses alone for now.
