### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sakinshrestha** [strangerstudios/memberlite#44]
* In `front-page.php` line 20 why is using `get_template_part` complicated here? Whats the reason?
* Maybe you can use something as follows to remove this code block:
```
function themeslug_filter_front_page_template( $template ) {
	return ( is_front_page() && basename( $template ) != 'page.php'  ) ? '' : $template;
}
add_filter( 'frontpage_template', 'themeslug_filter_front_page_template' );
```
This will allow page templates in front page and take `front-page.php` when there is no template selected.

**Comment by justintadlock** [comment]
It seems to me like you're attempting to overwrite the template hierarchy to allow the front page to do this:

* If is posts page, use normal `home.php`.
* If is front page with an assigned page template, use the custom template.
* Else, fall back to your custom `front-page.php` output.

A simpler way to do this would be to add a custom filter on the `frontpage_template_hierarchy` filter hook.  Here's a look at how I handle that exact scenario in my own themes if you want to check it out: https://github.com/justintadlock/hybrid-core/blob/master/inc/class-template-hierarchy.php#L81-L114 (note: use `get_page_template_slug()` instead of `hybrid_get_post_template()`).

**Comment by kimcoleman** [comment]
I have proposed code in place that @andrewlimaza is reviewing and will do a PR for when tested.

**Comment by kimcoleman** [comment]
Solved in PR https://github.com/strangerstudios/memberlite/pull/80
